### ISSUE TITLE
example-seaexplorer doesn't run successfully (ubuntu 18.10 if it matters)

### ISSUE THREAD

**Issue by richardsc** [jklymak/pyglider#7]
## What I did

* cloned the repo
* installed `pyglider` as instructed on the readme
* did the `pip install -e .` command 
* went into the `example-seaexplorer/` folder
* ran `python process_deploymentRealTime.py` at the command line

## What happened?

The processing script didn't not complete successfully. See output below:

<details><summary>Output</summary>

```
$ python process_deploymentRealTime.py  
rm: cannot remove './L1-timeseries/*': No such file or directory
rm: cannot remove './L1-profiles/*': No such file or directory
rm: cannot remove './L2-gridfiles/*': No such file or directory
./realtime_rawnc/
[]
INFO:pyglider.seaexplorer:All done!
['./realtime_raw/sea035.12.gli.sub.36', './realtime_raw/sea035.12.gli.sub.37', './realtime_raw/sea035.12.gli.sub.38', './realtime_raw/sea035.12.gli.sub.39', './realtime_raw/sea035.12.gli.sub.40', './realtime_raw/sea035.12.gli.sub.41', './realtime_raw/sea035.12.gli.sub.42', './realtime_raw/sea035.12.gli.sub.43', './realtime_raw/sea035.12.gli.sub.44', './realtime_raw/sea035.12.gli.sub.45', './realtime_raw/sea035.12.gli.sub.46', './realtime_raw/sea035.12.gli.sub.47', './realtime_raw/sea035.12.gli.sub.48', './realtime_raw/sea035.12.gli.sub.49']
['sea035', '12', 'gli', 'sub', '36']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.36 to ./realtime_rawnc/sea035.0012.gli.sub.0036.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.36 to ./realtime_rawnc/sea035.0012.gli.sub.0036.nc
['sea035', '12', 'gli', 'sub', '37']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.37 to ./realtime_rawnc/sea035.0012.gli.sub.0037.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.37 to ./realtime_rawnc/sea035.0012.gli.sub.0037.nc
['sea035', '12', 'gli', 'sub', '38']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.38 to ./realtime_rawnc/sea035.0012.gli.sub.0038.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.38 to ./realtime_rawnc/sea035.0012.gli.sub.0038.nc
['sea035', '12', 'gli', 'sub', '39']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.39 to ./realtime_rawnc/sea035.0012.gli.sub.0039.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.39 to ./realtime_rawnc/sea035.0012.gli.sub.0039.nc
['sea035', '12', 'gli', 'sub', '40']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.40 to ./realtime_rawnc/sea035.0012.gli.sub.0040.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.40 to ./realtime_rawnc/sea035.0012.gli.sub.0040.nc
['sea035', '12', 'gli', 'sub', '41']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.41 to ./realtime_rawnc/sea035.0012.gli.sub.0041.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.41 to ./realtime_rawnc/sea035.0012.gli.sub.0041.nc
['sea035', '12', 'gli', 'sub', '42']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.42 to ./realtime_rawnc/sea035.0012.gli.sub.0042.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.42 to ./realtime_rawnc/sea035.0012.gli.sub.0042.nc
['sea035', '12', 'gli', 'sub', '43']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.43 to ./realtime_rawnc/sea035.0012.gli.sub.0043.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.43 to ./realtime_rawnc/sea035.0012.gli.sub.0043.nc
['sea035', '12', 'gli', 'sub', '44']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.44 to ./realtime_rawnc/sea035.0012.gli.sub.0044.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.44 to ./realtime_rawnc/sea035.0012.gli.sub.0044.nc
['sea035', '12', 'gli', 'sub', '45']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.45 to ./realtime_rawnc/sea035.0012.gli.sub.0045.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.45 to ./realtime_rawnc/sea035.0012.gli.sub.0045.nc
['sea035', '12', 'gli', 'sub', '46']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.46 to ./realtime_rawnc/sea035.0012.gli.sub.0046.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.46 to ./realtime_rawnc/sea035.0012.gli.sub.0046.nc
['sea035', '12', 'gli', 'sub', '47']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.47 to ./realtime_rawnc/sea035.0012.gli.sub.0047.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.47 to ./realtime_rawnc/sea035.0012.gli.sub.0047.nc
['sea035', '12', 'gli', 'sub', '48']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.48 to ./realtime_rawnc/sea035.0012.gli.sub.0048.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.48 to ./realtime_rawnc/sea035.0012.gli.sub.0048.nc
['sea035', '12', 'gli', 'sub', '49']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.gli.sub.49 to ./realtime_rawnc/sea035.0012.gli.sub.0049.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.gli.sub.49 to ./realtime_rawnc/sea035.0012.gli.sub.0049.nc
INFO:pyglider.seaexplorer:All done!
[]
INFO:pyglider.seaexplorer:All done!
['./realtime_raw/sea035.12.pld1.sub.36', './realtime_raw/sea035.12.pld1.sub.37', './realtime_raw/sea035.12.pld1.sub.38', './realtime_raw/sea035.12.pld1.sub.39', './realtime_raw/sea035.12.pld1.sub.40', './realtime_raw/sea035.12.pld1.sub.41', './realtime_raw/sea035.12.pld1.sub.42', './realtime_raw/sea035.12.pld1.sub.43', './realtime_raw/sea035.12.pld1.sub.44', './realtime_raw/sea035.12.pld1.sub.45', './realtime_raw/sea035.12.pld1.sub.46', './realtime_raw/sea035.12.pld1.sub.47', './realtime_raw/sea035.12.pld1.sub.48', './realtime_raw/sea035.12.pld1.sub.49']
['sea035', '12', 'pld1', 'sub', '36']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.36 to ./realtime_rawnc/sea035.0012.pld1.sub.0036.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.36 to ./realtime_rawnc/sea035.0012.pld1.sub.0036.nc
['sea035', '12', 'pld1', 'sub', '37']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.37 to ./realtime_rawnc/sea035.0012.pld1.sub.0037.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.37 to ./realtime_rawnc/sea035.0012.pld1.sub.0037.nc
['sea035', '12', 'pld1', 'sub', '38']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.38 to ./realtime_rawnc/sea035.0012.pld1.sub.0038.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.38 to ./realtime_rawnc/sea035.0012.pld1.sub.0038.nc
['sea035', '12', 'pld1', 'sub', '39']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.39 to ./realtime_rawnc/sea035.0012.pld1.sub.0039.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.39 to ./realtime_rawnc/sea035.0012.pld1.sub.0039.nc
['sea035', '12', 'pld1', 'sub', '40']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.40 to ./realtime_rawnc/sea035.0012.pld1.sub.0040.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.40 to ./realtime_rawnc/sea035.0012.pld1.sub.0040.nc
['sea035', '12', 'pld1', 'sub', '41']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.41 to ./realtime_rawnc/sea035.0012.pld1.sub.0041.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.41 to ./realtime_rawnc/sea035.0012.pld1.sub.0041.nc
['sea035', '12', 'pld1', 'sub', '42']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.42 to ./realtime_rawnc/sea035.0012.pld1.sub.0042.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.42 to ./realtime_rawnc/sea035.0012.pld1.sub.0042.nc
['sea035', '12', 'pld1', 'sub', '43']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.43 to ./realtime_rawnc/sea035.0012.pld1.sub.0043.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.43 to ./realtime_rawnc/sea035.0012.pld1.sub.0043.nc
['sea035', '12', 'pld1', 'sub', '44']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.44 to ./realtime_rawnc/sea035.0012.pld1.sub.0044.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.44 to ./realtime_rawnc/sea035.0012.pld1.sub.0044.nc
['sea035', '12', 'pld1', 'sub', '45']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.45 to ./realtime_rawnc/sea035.0012.pld1.sub.0045.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.45 to ./realtime_rawnc/sea035.0012.pld1.sub.0045.nc
['sea035', '12', 'pld1', 'sub', '46']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.46 to ./realtime_rawnc/sea035.0012.pld1.sub.0046.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.46 to ./realtime_rawnc/sea035.0012.pld1.sub.0046.nc
['sea035', '12', 'pld1', 'sub', '47']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.47 to ./realtime_rawnc/sea035.0012.pld1.sub.0047.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.47 to ./realtime_rawnc/sea035.0012.pld1.sub.0047.nc
['sea035', '12', 'pld1', 'sub', '48']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.48 to ./realtime_rawnc/sea035.0012.pld1.sub.0048.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.48 to ./realtime_rawnc/sea035.0012.pld1.sub.0048.nc
['sea035', '12', 'pld1', 'sub', '49']
INFO:pyglider.seaexplorer:./realtime_raw/sea035.12.pld1.sub.49 to ./realtime_rawnc/sea035.0012.pld1.sub.0049.nc
INFO:pyglider.seaexplorer:Doing: ./realtime_raw/sea035.12.pld1.sub.49 to ./realtime_rawnc/sea035.0012.pld1.sub.0049.nc
INFO:pyglider.seaexplorer:All done!
id dfo-eva
INFO:pyglider.seaexplorer:Opening *.gli.sub.*.nc multi-file dataset from ./realtime_rawnc/
INFO:pyglider.seaexplorer:Done writing ./realtime_rawnc//dfo-eva-rawgli.nc
INFO:pyglider.seaexplorer:Working on gpctd
INFO:pyglider.seaexplorer:Working on flbbcd
INFO:pyglider.seaexplorer:Working on AROD
/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/dask/array/numpy_compat.py:39: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
INFO:pyglider.seaexplorer:Done merge_rawnc
Traceback (most recent call last):
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/mnt/c/Users/richardsc/src/pyglider_test/pyglider/example-seaexplorer/realtime_rawnc/dfo-eva035-rawgli.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/richardsc/src/pyglider_test/pyglider/example-seaexplorer/process_deploymentRealTime.py", line 35, in <module>
    outname = seaexplorer.raw_to_L1timeseries(rawncdir, l1tsdir, deploymentyaml, kind='sub')
  File "/mnt/c/Users/richardsc/src/pyglider_test/pyglider/pyglider/seaexplorer.py", line 259, in raw_to_L1timeseries
    gli = xr.open_dataset(indir + '/' + id + '-rawgli.nc', decode_times=False)
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/api.py", line 554, in open_dataset
    store = opener(filename_or_obj, **extra_kwargs, **backend_kwargs)
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 378, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 326, in __init__
    self.format = self.ds.data_model
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 387, in ds
    return self._acquire()
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 381, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/home/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/mnt/c/Users/richardsc/src/pyglider_test/pyglider/example-seaexplorer/realtime_rawnc/dfo-eva035-rawgli.nc'
```

**Comment by richardsc** [comment]
These are the files that were created before the script failed:
```
$ ls realtime_rawnc
dfo-eva-rawgli.nc*                    sea035.0012.pld1.sub.0040_arod.nc*
dfo-eva-subp_arod.nc*                 sea035.0012.pld1.sub.0040_flbbcd.nc*
dfo-eva-subp_flbbcd.nc*               sea035.0012.pld1.sub.0040_gpctd.nc*
dfo-eva-subp_gpctd.nc*                sea035.0012.pld1.sub.0041_arod.nc*
sea035.0012.gli.sub.0036.nc*          sea035.0012.pld1.sub.0041_flbbcd.nc*
sea035.0012.gli.sub.0037.nc*          sea035.0012.pld1.sub.0041_gpctd.nc*
sea035.0012.gli.sub.0038.nc*          sea035.0012.pld1.sub.0042_arod.nc*
sea035.0012.gli.sub.0039.nc*          sea035.0012.pld1.sub.0042_flbbcd.nc*
sea035.0012.gli.sub.0040.nc*          sea035.0012.pld1.sub.0042_gpctd.nc*
sea035.0012.gli.sub.0041.nc*          sea035.0012.pld1.sub.0043_arod.nc*
sea035.0012.gli.sub.0042.nc*          sea035.0012.pld1.sub.0043_flbbcd.nc*
sea035.0012.gli.sub.0043.nc*          sea035.0012.pld1.sub.0043_gpctd.nc*
sea035.0012.gli.sub.0044.nc*          sea035.0012.pld1.sub.0044_arod.nc*
sea035.0012.gli.sub.0045.nc*          sea035.0012.pld1.sub.0044_flbbcd.nc*
sea035.0012.gli.sub.0046.nc*          sea035.0012.pld1.sub.0044_gpctd.nc*
sea035.0012.gli.sub.0047.nc*          sea035.0012.pld1.sub.0045_arod.nc*
sea035.0012.gli.sub.0048.nc*          sea035.0012.pld1.sub.0045_flbbcd.nc*
sea035.0012.gli.sub.0049.nc*          sea035.0012.pld1.sub.0045_gpctd.nc*
sea035.0012.pld1.sub.0036_arod.nc*    sea035.0012.pld1.sub.0046_arod.nc*
sea035.0012.pld1.sub.0036_flbbcd.nc*  sea035.0012.pld1.sub.0046_flbbcd.nc*
sea035.0012.pld1.sub.0036_gpctd.nc*   sea035.0012.pld1.sub.0046_gpctd.nc*
sea035.0012.pld1.sub.0037_arod.nc*    sea035.0012.pld1.sub.0047_arod.nc*
sea035.0012.pld1.sub.0037_flbbcd.nc*  sea035.0012.pld1.sub.0047_flbbcd.nc*
sea035.0012.pld1.sub.0037_gpctd.nc*   sea035.0012.pld1.sub.0047_gpctd.nc*
sea035.0012.pld1.sub.0038_arod.nc*    sea035.0012.pld1.sub.0048_arod.nc*
sea035.0012.pld1.sub.0038_flbbcd.nc*  sea035.0012.pld1.sub.0048_flbbcd.nc*
sea035.0012.pld1.sub.0038_gpctd.nc*   sea035.0012.pld1.sub.0048_gpctd.nc*
sea035.0012.pld1.sub.0039_arod.nc*    sea035.0012.pld1.sub.0049_arod.nc*
sea035.0012.pld1.sub.0039_flbbcd.nc*  sea035.0012.pld1.sub.0049_flbbcd.nc*
sea035.0012.pld1.sub.0039_gpctd.nc*   sea035.0012.pld1.sub.0049_gpctd.nc*
```

**Comment by richardsc** [comment]
Aside from the "invalid value" warning, it looks to be related to the fact that `raw_to_L1timeseries()` is looking for the file `dfo-eva035-rawgli.nc` but actually the file is `dfo-eva-rawgli.nc` (i.e. without the `035`).

**Comment by jklymak** [comment]
Likely the deployment.yml has changed a bit so that the glider name should be `eva035` not just `eva`.  Sorry, how that all worked was under flux at some point.

**Comment by richardsc** [comment]
Hm, I see some commented lines with e.g.
```python
    id = metadata['glider_name'] # + metadata['glider_serial']
```
but not commented in other spots.

Removing the comments at the two places they exist, e.g. see diff below, gets it past this error (but lands on another one -- see next comment).
```
$ git diff
diff --git a/pyglider/seaexplorer.py b/pyglider/seaexplorer.py
index 4cab412..e8159e7 100644
--- a/pyglider/seaexplorer.py
+++ b/pyglider/seaexplorer.py
@@ -177,7 +177,7 @@ def merge_rawnc(indir, outdir, deploymentyaml, incremental=False, kind='raw'):
     with open(deploymentyaml) as fin:
         deployment = yaml.safe_load(fin)
     metadata = deployment['metadata']
-    id = metadata['glider_name'] # + metadata['glider_serial']
+    id = metadata['glider_name'] + metadata['glider_serial']
     print('id', id)
     outgli = outdir + '/' + id + '-rawgli.nc'
     outpld = outdir + '/' + id + '-' + kind + 'pld.nc'
@@ -363,7 +363,7 @@ def raw_to_L1timeseries_raw(indir, outdir, deploymentyaml, kind='raw',
     metadata = deployment['metadata']
     ncvar = deployment['netcdf_variables']
 
-    id = metadata['glider_name']  # + metadata['glider_serial']
+    id = metadata['glider_name'] + metadata['glider_serial']
     gli = xr.open_dataset(indir + '/' + id + '-rawgli.nc', decode_times=False)
     ctd = xr.open_dataset(indir + '/' + id + '-' + kind+ 'p_gpctd.nc',
                           decode_times=False)
```

**Comment by richardsc** [comment]
Ok, after the above fix, it now fails with a similar error, but regarding a missing `dfo-eva035-subpld.nc`:
```
/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/dask/array/numpy_compat.py:39: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
INFO:pyglider.seaexplorer:Done merge_rawnc
Traceback (most recent call last):
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/Users/richardsc/src/pyglider/example-seaexplorer/realtime_rawnc/dfo-eva035-subpld.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardsc/src/pyglider/example-seaexplorer/process_deploymentRealTime.py", line 35, in <module>
    outname = seaexplorer.raw_to_L1timeseries(rawncdir, l1tsdir, deploymentyaml, kind='sub')
  File "/Users/richardsc/src/pyglider/pyglider/seaexplorer.py", line 260, in raw_to_L1timeseries
    pld = xr.open_dataset(indir + '/' + id + '-' + kind+ 'pld.nc',
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/api.py", line 554, in open_dataset
    store = opener(filename_or_obj, **extra_kwargs, **backend_kwargs)
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 378, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 326, in __init__
    self.format = self.ds.data_model
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 387, in ds
    return self._acquire()
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 381, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 187, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/Users/richardsc/miniconda3/envs/pyglider/lib/python3.9/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2330, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1948, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/Users/richardsc/src/pyglider/example-seaexplorer/realtime_rawnc/dfo-eva035-subpld.nc'
```

**Comment by richardsc** [comment]
Looks like the `dfo-eva035-subpld.nc` doesn't exist because its creation is under a conditional requiring `kind == 'boo'`. Not sure what that is ... 

See lines 182-224 in `seaexplorer.py`:
```python
    outgli = outdir + '/' + id + '-rawgli.nc'
    outpld = outdir + '/' + id + '-' + kind + 'pld.nc'

    _log.info('Opening *.gli.sub.*.nc multi-file dataset from %s', indir)
    files = sorted(glob.glob(indir+'/*.gli.sub.*.nc'))
    with xr.open_dataset(files[0], decode_times=False) as gli:
        for fil in files[1:]:
            try:
                with xr.open_dataset(fil, decode_times=False) as gli2:
                    gli = xr.concat([gli, gli2], dim='time')
            except:
                pass
        gli.to_netcdf(outgli)
    _log.info(f'Done writing {outgli}')

    if kind == 'boo':
        _log.info('Opening *.pld.sub.*.nc multi-file dataset')
        files = sorted(glob.glob(indir+'/*.pld1.'+kind+'.*.nc'))
        with xr.open_dataset(files[0], decode_times=False) as pld:
            for fil in files[1:]:
                try:
                    with xr.open_dataset(fil, decode_times=False) as pld2:
                        pld = xr.concat([pld, pld2], dim='time')
                except:
                    pass
            _log.info('Writing ' + outpld)
            pld.to_netcdf(outpld)
    else:
        _log.info('Working on gpctd')
        with xr.open_mfdataset(f'{indir}/*.{kind}*gpctd.nc', combine='nested',
                               concat_dim='time', decode_times=False) as pld:
            pld.to_netcdf(outpld[:-5]+'_gpctd.nc')
        _log.info('Working on flbbcd')
        with xr.open_mfdataset(f'{indir}/*.{kind}*flbbcd.nc', combine='nested',
                               concat_dim='time', decode_times=False) as pld:
            pld.to_netcdf(outpld[:-5]+'_flbbcd.nc')
        _log.info('Working on AROD')
        with xr.open_mfdataset(f'{indir}/*.{kind}*arod.nc', combine='nested',
                       concat_dim='time', decode_times=False) as pld:
            pld = pld.coarsen(time=8, boundary='trim').mean()
            pld.to_netcdf(outpld[:-5]+'_arod.nc')

    _log.info('Done merge_rawnc')
```

**Comment by jklymak** [comment]
Yep, its calling the wrong version of that routine.  Checkout the latest push

**Comment by richardsc** [comment]
That did it. Thanks!

**Comment by jklymak** [comment]
Yeah, sorry, apparently I changed some of it, but then didn't use the same name for the new script.  I need to clean up a fair bit.
